export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PRODUCTS_SUCCESS='LOAD_PRODUCTS_SUCCESS';
export const CREATE_PRODUCT_SUCCESS='CREATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS='UPDATE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS';
